### ISSUE TITLE
CSwin Code for Segmentation with MMSegmentation

### ISSUE THREAD

**Issue by WalBouss** [microsoft/CSWin-Transformer#15]
Hi,
Thank you for your work!
I wonder if you plan to release the mmsegmentation code you used for the downstream segmentation task, just like in [Swin-Transformer](https://github.com/SwinTransformer/Swin-Transformer-Semantic-Segmentation) repo.

Best,

**Comment by LightDXY** [comment]
code and models released, please create a new issue for any new problems.
