### ISSUE TITLE
I tested several segmentation data, and I doubt your performance

### ISSUE THREAD

**Issue by zhouyi-git** [microsoft/CSWin-Transformer#20]

**Comment by matt022899** [comment]
Also I noticed many issues concerning the same problem. The best way to prove the effectiveness of the backbone is to release the config and training log of the downstream tasks as Swin Transformer and PVT do. As the paper said, they used default configs  , thus does not involve any commercial secrets to just release the logs of training and configs. I hope the authors could reply positively to make it convinced.

**Comment by AnukritiSinghh** [comment]
We too noticed the inconsistency. The result we are able to replicate is at least 4 points less than that claimed in the paper.

**Comment by wujiang0156** [comment]
I hope the authors could reply positively to make it convinced.

**Comment by wujiang0156** [comment]
I tested ade20k, and I doubt your performance , this mode is not better than swin transformer
