### ISSUE TITLE
how to set param drop-path for base and large model?

### ISSUE THREAD

**Issue by zimenglan-sysu-512** [microsoft/CSWin-Transformer#4]
hi @LightDXY 
how to set param drop-path for base and large model? and also when finetune on 384x384 input size?

**Comment by LightDXY** [comment]
Hi, we set the drop path rate=0.5 for the base model and we only train the large model on the IamgeNet22k.

When finetuning on 384x384 images, a drop path rate slightly larger than the pretraining setting should be better.

**Comment by zimenglan-sysu-512** [comment]
thanks
