### ISSUE TITLE
The problem is shown in the figure

### ISSUE THREAD

**Issue by rui-cf** [microsoft/CSWin-Transformer#5]
model = CSWinTransformer(patch_size=4, embed_dim=96, depth=[2,4,32,2],
        split_size=[1,2,12,12], num_heads=[4,8,16,32], mlp_ratio=4.).cuda().eval()
inp = torch.rand(1, 3, 224, 224).cuda()
outs = model(inp)
for out in outs:
    print(out.shape)

RuntimeError: shape '[1, 192, 1, 14, 1, 12]' is invalid for input of size 37632

why?
![image](https://user-images.githubusercontent.com/54253581/127121818-80d9faed-e9d8-49d0-9e17-69c3a1e8707d.png)

**Comment by LightDXY** [comment]
The feature map size should be divisible by the split size. For example, with image_size=224, the feature map size of stage 3 is 14, and the default split size is 7. We use split size=12 for input image size=384. 

We add padding to realize a flexible split size for downstream tasks, but we do not consider it in the ImageNet model because the padding is not efficient.

**Comment by 506813254** [comment]
> The feature map size should be divisible by the split size. For example, with image_size=224, the feature map size of stage 3 is 14, and the default split size is 7. We use split size=12 for input image size=384.
> 
> We add padding to realize a flexible split size for downstream tasks, but we do not consider it in the ImageNet model because the padding is not efficient.

Hi，What does the padding do？

**Comment by 54wb** [comment]
> > The feature map size should be divisible by the split size. For example, with image_size=224, the feature map size of stage 3 is 14, and the default split size is 7. We use split size=12 for input image size=384.
> > We add padding to realize a flexible split size for downstream tasks, but we do not consider it in the ImageNet model because the padding is not efficient.
> 
> Hi，What does the padding do？

hi, do you know what does the padding do or how can i find the padding code

**Comment by wujiang0156** [comment]
![image](https://github.com/microsoft/CSWin-Transformer/assets/7938373/0c2218de-6cc7-400d-b495-50325498a5a5)
![image](https://github.com/microsoft/CSWin-Transformer/assets/7938373/8e026cb0-b0ac-4b94-be8b-deb048b63cdc)
the table's list is as same as the code. which is right? thank you
