### ISSUE TITLE
Error about building 384 models

### ISSUE THREAD

**Issue by TingquanGao** [microsoft/CSWin-Transformer#6]
The code: https://github.com/microsoft/CSWin-Transformer/blob/d8be74a7833898f7bd9c77eb8c051d1b8bd5d753/models/cswin.py#L407
shoud be:
```python
model = CSWinTransformer(img_size=384, patch_size=4, embed_dim=96, depth=[2,4,32,2],
```
And as the same:
https://github.com/microsoft/CSWin-Transformer/blob/d8be74a7833898f7bd9c77eb8c051d1b8bd5d753/models/cswin.py#L414

**Comment by LightDXY** [comment]
We set the image size as an input parameter.
https://github.com/microsoft/CSWin-Transformer/blob/d8be74a7833898f7bd9c77eb8c051d1b8bd5d753/main.py#L312

and as the same
https://github.com/microsoft/CSWin-Transformer/blob/d8be74a7833898f7bd9c77eb8c051d1b8bd5d753/finetune.py#L449

**Comment by TingquanGao** [comment]
OK, thx for reply.
