### ISSUE TITLE
Pretrained settings for object detection

### ISSUE THREAD

**Issue by youngwanLEE** [microsoft/CSWin-Transformer#8]
Hi, I'm impressed by your excellent work.

I have a question.

I wonder which type of the pre-trained weights (224x224 or 384x384 finetuned) is used for object detection.

I know both 224x224 and 384x384 are pre-trained on ImageNet-1k.

**Comment by LightDXY** [comment]
Hi, thanks for your interest in our work, we use the 224x224 pretrained model for both detection and segmentation.

**Comment by youngwanLEE** [comment]
@LightDXY Thanks for reply :)
